### ISSUE TITLE
Not loading into Foundry

### ISSUE THREAD

**Issue by newbyr** [jrommann/knave#15]
HI

When I try to load the system into Foundry I get an error "Installation failed : k is undefined".  THis is for the auto loaded manifest "https://raw.githubusercontent.com/jrommann/knave/master/system.json"

When I enter a direct link to manifest as "https://github.com/jrommann/knave/blob/master/system.json" the error message is "https://github.com/jrommann/knave/blob/master/system.json  did not provide a valid manifest file"

Any advice ??

Thanks
Richard

**Comment by jrommann** [comment]
Fixed, but you need foundry v10

**Comment by jrommann** [comment]
I'll get a working release for v9 this week

**Comment by jrommann** [comment]
you can use this manifest link to get KNAVE for Foundry v9
https://raw.githubusercontent.com/jrommann/knave/foundry_v9/system.json

**Comment by newbyr** [comment]
Thank you
