### ISSUE TITLE
Item Drop Down

### ISSUE THREAD

**Issue by PestoPosta** [jrommann/knave#16]
This is a suggestion (a quality of life issue if you will).

It would be really really helpful to be able to click on an item name box
![image](https://user-images.githubusercontent.com/15177759/190944375-04c5f742-2451-4043-922a-0c5ca307b8ec.png)

and then have a uneditable drop down with the items info.
![image](https://user-images.githubusercontent.com/15177759/190944440-c0b74211-10ae-4514-b047-bb48ca978543.png)

As items are currently the only way to add abilities which are sectioned off as an ability.

**Comment by PestoPosta** [comment]
PS, thanks for adding Knave to Foundry.

**Comment by jrommann** [comment]
Implemented in v9

**Comment by PestoPosta** [comment]
Awesome :)
