### ISSUE TITLE
Character sheet is not loading on Firefox

### ISSUE THREAD

**Issue by Dr-KerbalMD** [jrommann/knave#4]
Screenshot attached. Works fine in Chrome.

![image](https://user-images.githubusercontent.com/20614697/106226783-fb6afe00-61b5-11eb-994f-d2915aa39f47.png)

**Comment by jrommann** [comment]
I've looked at the console in Firefox and can find now errors. Tried a few things with changing the sheet HTML and it does not change in Firefox, so for now this is a issue specific to Firefox.

The sheet works fine in Chrome, Opera and Foundry.
